-- Project Kestrel - migration 001 (BASELINE)
--
-- The procedure exactly as deployed in Supabase on 12 September 2026, captured
-- verbatim via pg_get_functiondef(). Do not edit this file. It exists so the
-- repository has a recoverable starting point and so the diff against
-- migration 003 is auditable.
--
-- Known defects, all corrected in 003:
--   1. The passenger's previous seat is never released back to AVAILABLE.
--   2. The target flight is never validated (existence, status, departure time).
--   3. Repeat invocations issue a second seat instead of being rejected.
--   4. Failed attempts write no audit row.
--   5. ORDER BY seat_number is a lexicographic sort, so 10A precedes 2A.

CREATE OR REPLACE FUNCTION public.reaccommodate_passenger_atomic(
    p_pnr_code character varying,
    p_target_flight_id uuid,
    p_actor character varying DEFAULT 'AGENT_AI'::character varying
)
RETURNS TABLE(success boolean, assigned_seat_number character varying, message text)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_seat_id UUID;
    v_seat_num VARCHAR(5);
    v_passenger_id UUID;
BEGIN
    -- Validate PNR
    SELECT passenger_id INTO v_passenger_id
    FROM pnr_bookings
    WHERE pnr_code = p_pnr_code;

    IF v_passenger_id IS NULL THEN
        RETURN QUERY SELECT FALSE, NULL::VARCHAR, 'Invalid PNR code provided.'::TEXT;
        RETURN;
    END IF;

    -- Lock and claim the first available seat
    SELECT seat_id, seat_number INTO v_seat_id, v_seat_num
    FROM seats
    WHERE flight_id = p_target_flight_id
    AND status = 'AVAILABLE'
    ORDER BY seat_number ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1;

    IF v_seat_id IS NULL THEN
        RETURN QUERY SELECT FALSE, NULL::VARCHAR, 'No available seats remaining on the target flight.'::TEXT;
        RETURN;
    END IF;

    -- Update Seat
    UPDATE seats
    SET status = 'BOOKED', row_version = row_version + 1
    WHERE seat_id = v_seat_id;

    -- Update Booking
    UPDATE pnr_bookings
    SET reaccommodated_flight_id = p_target_flight_id,
        assigned_seat_id = v_seat_id,
        booking_status = 'REACCOMMODATED',
        updated_at = CURRENT_TIMESTAMP
    WHERE pnr_code = p_pnr_code;

    -- Audit Log Entry
    INSERT INTO audit_logs (pnr_code, actor, action, details)
    VALUES (
        p_pnr_code,
        p_actor,
        'AUTOMATED_REACCOMMODATION',
        jsonb_build_object(
            'target_flight_id', p_target_flight_id,
            'assigned_seat', v_seat_num,
            'assigned_seat_id', v_seat_id
        )
    );

    RETURN QUERY SELECT TRUE, v_seat_num, 'Passenger re-accommodated successfully.'::TEXT;
END;
$function$;